version: 2

jobs:
  startup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Build for production
          command: yarn build:production

      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - '31:70:e1:93:08:c5:72:8e:3f:14:a5:20:44:7a:ca:f7'

      - restore_cache:
          name: 'Restored dependencies'
          key: yarn-{{ checksum "yarn.lock" }}

      - restore_cache:
          name: 'Restored distribution files'
          key: dist-{{ .Revision }}

      - run:
          name: Set git user info
          command: |
            git config user.name $GIT_USER_NAME
            git config user.email $GIT_USER_EMAIL
      - run:
          name: Deploy to gh-pages
          command: yarn deploy

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - startup:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - startup
      - test:
          requires:
            - startup
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
